services:
  finnhub.sqldb:
    image: bitnami/postgresql:latest
    container_name: finnhub.sqldb
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
    volumes:
      - postgresql_data:/bitnami/postgresql

  finnhub.nosqldb:
    image: bitnami/mongodb:latest
    container_name: finnhub.nosqldb
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin123
      - MONGODB_USERNAME=finnhub_user
      - MONGODB_PASSWORD=finnhub_pass
      - MONGODB_DATABASE=finnhub_db
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
  postgresql_data: