name: Market Data
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/contexts/market-data/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/contexts/market-data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: |
          cd src/contexts/market-data
          dotnet restore

    - name: Build
      run: |
        cd src/contexts/market-data
        dotnet build --no-restore

    - name: Test
      run: |
        cd src/contexts/market-data
        dotnet test --no-build --verbosity normal

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Market Data image
        uses: docker/build-push-action@v5
        with:
          context: ./src/contexts/market-data
          file: ./src/contexts/market-data/src/FinnHub.MarketData.WebApi/Dockerfile
          push: true
          tags: raffreitas/finnhub-market-data:latest

      - name: Build and push Market Data Ingestion Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/contexts/market-data
          file: ./src/contexts/market-data/src/FinnHub.MarketData.Ingestion/Dockerfile
          push: true
          tags: raffreitas/finnhub-market-data-ingestion:latest
      
      - name: Build and push Market Data Processor Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/contexts/market-data
          file: ./src/contexts/market-data/src/FinnHub.MarketData.Processor/Dockerfile
          push: true
          tags: raffreitas/finnhub-market-data-processor:latest
