name: Portfolio Management
on:
  push:
    branches: [main]
    paths:
      - 'src/contexts/portfolio-management/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/contexts/portfolio-management/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x

    - name: Restore dependencies
      run: |
          cd src/contexts/portfolio-management
          dotnet restore

    - name: Build
      run: |
        cd src/contexts/portfolio-management
        dotnet build --no-restore

    - name: Test
      run: |
        cd src/contexts/portfolio-management
        dotnet test --no-build --verbosity normal

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/contexts/portfolio-management
          file: ./src/contexts/portfolio-management/src/FinnHub.PortfolioManagement.WebApi/Dockerfile
          push: true
          tags: raffreitas/finnhub-portfolio-management:latest
